# 使用Node官方镜像
FROM node:20-slim

# 设置工作目录
WORKDIR /app

# 复制package.json和package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制项目代码
COPY . .

# 暴露端口
EXPOSE 5173

# 默认启动命令
CMD ["npm", "run", "dev"]